import type { SpeciesId } from "./schema";

/**
 * Curated fly collections that map onto Shopify collections. The Two Hearted
 * list was generated by `pnpm exec tsx scripts/river-batch.ts two-hearted --top 4 --min 45 --json`
 * (top four flies per month x species x setup with score >= 45) and then hand-edited.
 * Edit freely; the script is a starting point, not a source of truth.
 */

export interface CollectionFly {
  flyId: string;
  /** Months the fly finder calls for this fly on the collection river. */
  months: number[];
  forSpecies: SpeciesId[];
}

export interface Collection {
  id: string;
  title: string;
  description: string;
  riverId?: string;
  /** Shopify collection handle; products in the batch carry the tag `collection:<id>`. */
  shopifyHandle: string;
  status: "coming-soon" | "live";
  flies: CollectionFly[];
}

export const collections: Collection[] = [
  {
    id: "two-hearted-first-batch",
    title: "Two Hearted River box",
    description:
      "Our first batch: the 55 patterns the Two Hearted calls for across the year, from spring steelhead eggs and stonefly nymphs through summer brook trout dries, Hex, and mice, to the fall Chinook, coho, and pink salmon run. Sized and colored for a Lake Superior freestone that runs two to three weeks behind the Au Sable.",
    riverId: "two-hearted",
    shopifyHandle: "two-hearted-river-box",
    status: "coming-soon",
    flies: [
      { flyId: "woolly-bugger", months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], forSpecies: ["brook-trout", "rainbow-trout", "steelhead", "chinook", "coho"] },
      { flyId: "zebra-midge", months: [1, 2, 3, 4, 6, 8, 9, 10, 11, 12], forSpecies: ["brook-trout", "rainbow-trout", "pink-salmon"] },
      { flyId: "muddler-minnow", months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], forSpecies: ["brook-trout", "rainbow-trout", "steelhead"] },
      { flyId: "soft-hackle-wet", months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "glo-bug", months: [4, 5, 8, 9, 10, 11], forSpecies: ["steelhead", "pink-salmon", "rainbow-trout", "chinook", "coho"] },
      { flyId: "green-caddis-larva", months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], forSpecies: ["rainbow-trout"] },
      { flyId: "egg-sucking-leech", months: [4, 5, 9, 10, 11], forSpecies: ["steelhead", "chinook", "coho"] },
      { flyId: "pats-rubber-legs", months: [4, 5, 6, 7, 8], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "wet-skunk", months: [5, 6, 7, 8, 9], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "griffiths-gnat", months: [1, 2, 3, 4, 6, 8, 9, 10, 11, 12], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "salmon-egg-cluster", months: [9, 10, 11], forSpecies: ["chinook", "coho", "steelhead"] },
      { flyId: "black-stonefly-nymph", months: [3, 4, 5], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "hares-ear-nymph", months: [5, 6, 7, 8, 9, 10], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "clown-egg", months: [4, 9, 10, 11], forSpecies: ["steelhead", "chinook", "coho"] },
      { flyId: "nuke-egg", months: [4, 8, 9, 10, 11], forSpecies: ["steelhead", "pink-salmon", "rainbow-trout", "chinook", "coho"] },
      { flyId: "pheasant-tail-nymph", months: [5, 7, 8, 9, 10, 11], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "sucker-spawn", months: [4, 5, 6], forSpecies: ["steelhead", "rainbow-trout"] },
      { flyId: "scud", months: [1, 2, 8, 9, 12], forSpecies: ["rainbow-trout", "pink-salmon"] },
      { flyId: "zoo-cougar", months: [3, 4, 5, 6, 8, 9, 10, 11], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "scrambled-eggs", months: [5, 9, 10, 11], forSpecies: ["steelhead", "rainbow-trout"] },
      { flyId: "circus-peanut", months: [3, 4, 5, 9, 10, 11], forSpecies: ["rainbow-trout", "steelhead"] },
      { flyId: "drunk-and-disorderly", months: [3, 4, 5, 6, 9, 10, 11], forSpecies: ["rainbow-trout", "steelhead"] },
      { flyId: "adams-parachute", months: [5, 6, 7, 8, 9], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "borchers-parachute", months: [5, 6, 7, 10, 11], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "san-juan-worm", months: [3, 4, 9, 10, 11], forSpecies: ["brook-trout"] },
      { flyId: "sex-dungeon", months: [3, 4, 5, 10, 11], forSpecies: ["rainbow-trout", "steelhead"] },
      { flyId: "hex-nymph", months: [6, 7], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "halloween-leech", months: [9, 10, 11], forSpecies: ["chinook", "coho", "steelhead"] },
      { flyId: "micro-spawn", months: [10, 11, 12], forSpecies: ["brook-trout"] },
      { flyId: "y2k-egg", months: [3, 4, 5], forSpecies: ["rainbow-trout", "steelhead"] },
      { flyId: "steelhead-bugger", months: [5, 9, 10, 11], forSpecies: ["steelhead", "chinook", "coho"] },
      { flyId: "bwo-parachute", months: [6, 8, 9], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "sowbug", months: [1, 2, 12], forSpecies: ["rainbow-trout"] },
      { flyId: "black-string-leech", months: [9, 10, 11], forSpecies: ["chinook", "coho"] },
      { flyId: "clouser-minnow", months: [9, 10, 11], forSpecies: ["chinook", "coho"] },
      { flyId: "eggstacy-egg", months: [4, 5], forSpecies: ["steelhead"] },
      { flyId: "elk-hair-caddis", months: [10, 11], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "giant-black-stonefly-nymph", months: [6, 7], forSpecies: ["brook-trout"] },
      { flyId: "twenty-incher", months: [6, 8], forSpecies: ["rainbow-trout"] },
      { flyId: "mahogany-dun-parachute", months: [10, 11], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "flying-ant", months: [8, 9], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "little-rascal", months: [3, 4, 10, 11], forSpecies: ["brook-trout"] },
      { flyId: "spring-wiggler", months: [7], forSpecies: ["rainbow-trout"] },
      { flyId: "morrish-mouse", months: [7, 8, 9], forSpecies: ["brook-trout"] },
      { flyId: "gurgler", months: [7, 8, 9], forSpecies: ["brook-trout"] },
      { flyId: "otters-soft-milking-egg", months: [10, 11], forSpecies: ["steelhead"] },
      { flyId: "regans-hendrickson-parachute", months: [5], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "regans-hendrickson-spinner", months: [5], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "hex-spinner", months: [7], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "mccoys-all-day-dun", months: [7], forSpecies: ["brook-trout", "rainbow-trout"] },
      { flyId: "sly-stone-wiggle", months: [3], forSpecies: ["rainbow-trout"] },
      { flyId: "sly-sister-stone", months: [3, 4], forSpecies: ["rainbow-trout"] },
      { flyId: "grapefruit-head-leech", months: [4, 11], forSpecies: ["steelhead"] },
      { flyId: "chinook-fry-streamer", months: [3, 4], forSpecies: ["rainbow-trout"] },
      { flyId: "pink-salmon-flash-nymph", months: [8, 9], forSpecies: ["pink-salmon"] },
    ],
  },
];

export const collectionById = new Map(collections.map((c) => [c.id, c]));
